repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: mixed-line-ending
    -   id: check-added-large-files
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout
